_target_: src.models.config.Siglip2Config
name: "google/siglip2-so400m-patch16-256" # Example
type: "siglip2"
feature_dim: 1152
layers: 27
patch_size: 16
register_tokens: 0
cls_token: false
model_part: "vision"
