# Native ALOE DINOv3 **small** (B-cos) + ImageNet-1k linear-probe checkpoints.

defaults:
  - /model/backbone/dinov3/aloe_dinov3_small_local_weights@_here_
  - _self_

num_labels: 1000
aloe_use_logit_layer: true
linear_probe_checkpoint: "${oc.env:CACHE_PATH}/aloe-align-once-to-explain/r1yuyzwu/checkpoints/best_lr=0.01.ckpt"
